services:
  app:
    image: auradvin/dotpics
    build: .
    container_name: dotpics_app
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - data_protection:/home/app/.aspnet/DataProtection-Keys
    ports:
      - "8080:8080" # internal app port
    depends_on:
      - redis
      - mongo


  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data


  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/app.conf.template:/etc/nginx/templates/app.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    command: /bin/sh -c "envsubst '$${APP_DOMAIN}'
        < /etc/nginx/templates/app.conf.template
        > /etc/nginx/conf.d/app.conf
        && nginx -g \"daemon off;\""
    depends_on:
      - app
        
  certbot-init:
    image: certbot/certbot
    container_name: certbot_init
    environment:
      APP_EMAIL: ${APP_EMAIL}
      APP_DOMAIN: ${APP_DOMAIN}
      CERTBOT_STAGING: ${CERTBOT_STAGING:-0}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: >
      -c "certbot certonly
      --webroot
      --webroot-path=/var/www/certbot
      --email $APP_EMAIL
      --agree-tos
      --no-eff-email
      -d $APP_DOMAIN
      --non-interactive
      $( [ \"$CERTBOT_STAGING\" = \"1\" ] && echo '--staging' )"
    depends_on:
      - nginx
        
  certbot-renew:
    image: certbot/certbot
    container_name: certbot_renew
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: >
      -c "trap exit TERM;
      while :; do
        certbot renew --webroot --webroot-path=/var/www/certbot --quiet;
        sleep 12h & wait $${!};
      done"
    depends_on:
      - nginx

volumes:
  mongo_data:
  redis_data:
  data_protection:
